# Generated by Django 4.2.13 on 2024-05-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="testImage",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/test_photos/%y/%m/%d/",
                verbose_name=" ფოტო",
            ),
        ),
    ]
