# Generated by Django 4.2.13 on 2024-07-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testsapp", "0002_category1_alter_category3_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category3",
            name="testImage",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/Category3_photos/%y/%m/%d/",
                verbose_name=" ფოტო",
            ),
        ),
    ]
