# Generated by Django 4.2.13 on 2024-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testsapp", "0002_alter_test_testimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="answers_image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/Answer_photos/%y/%m/%d/",
                verbose_name=" ფოტო",
            ),
        ),
    ]
