# Generated by Django 4.2.13 on 2024-07-04 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testsapp", "0003_category3_testimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category1",
            old_name="Category1_name",
            new_name="category1_name",
        ),
        migrations.RenameField(
            model_name="category2",
            old_name="Category1_name",
            new_name="category1_name",
        ),
        migrations.RenameField(
            model_name="category2",
            old_name="Category2_name",
            new_name="category2_name",
        ),
        migrations.RenameField(
            model_name="category3",
            old_name="Category2_name",
            new_name="category2_name",
        ),
        migrations.RenameField(
            model_name="category3",
            old_name="Category3_name",
            new_name="category3_name",
        ),
    ]
