# Generated by Django 4.2.13 on 2024-07-04 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testsapp", "0004_rename_category1_name_category1_category1_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category1",
            old_name="category1_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="category2",
            old_name="category2_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="category3",
            old_name="category3_name",
            new_name="name",
        ),
    ]
