# Generated by Django 4.2.13 on 2024-07-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testsapp", "0006_rename_category1_name_category2_category1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category2",
            name="testImage",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/Category3_photos/%y/%m/%d/",
                verbose_name=" ფოტო",
            ),
        ),
    ]
