# Generated by Django 4.2.13 on 2024-07-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testsapp", "0008_userident_coins_userident_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="product name")),
                ("price", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "productImage",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="photos/product_photos/%y/%m/%d/",
                        verbose_name=" პროდუქტის ფოტო",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
